# Generated by Django 2.2.5 on 2021-03-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.Task')),
            ],
        ),
    ]
