# Generated by Django 2.2.5 on 2021-03-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_taskparam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskparam',
            old_name='Task',
            new_name='task',
        ),
    ]
