# Generated by Django 2.2.5 on 2021-03-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_auto_20210312_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskParamName',
        ),
    ]
